const jewishHistory = [
	{ yearStart: -4004, yearEnd: -3000, event: "Adam and Eve"},
	{ yearStart: -3000, yearEnd: -2000, event: "Noah"},
	{yearStart: -2348, yearEnd: -2348, event: "The Great Flood"},
	{ yearStart: -2000, yearEnd: -1500, event: "Abraham"},
	{ yearStart: -1500, yearEnd: -1400, event: "Moses"},
	{ yearStart: -1400, yearEnd: -1000, event: "David"},
	{ yearStart: -1321, yearEnd: -1312, event: "Exodus from Egypt"},
	{ yearStart: 1250, yearEnd: 1025, event: "Biblical Judges"},
	{ yearStart: 1025, yearEnd: 1010, event: " King Saul"},
	{ yearStart: 1010, yearEnd: 970, event: "King David"},
	{ yearStart: -970, yearEnd: -931, event: "King Solomon"},
	{ yearStart: -960, yearEnd: -960, event: "First (King Solomon's)Temple Completed"},
	{ yearStart: -931, yearEnd: -931, event: "King Solomon Passed Away. Israel and Judah Split"},
	{ yearStart: -740, yearEnd: -700, event: "Isaiah"},
	{ yearStart: -722, yearEnd: -722, event: "Israel invaded by Assyrians"},
	{ yearStart: -715, yearEnd: -687, event: "Hezekiah"},
	{ yearStart: -650, yearEnd: -600, event: "Zephaniah"},
	{yearStart: -649, yearEnd: -609, event: "King Josiah"},
	{ yearStart: -626, yearEnd: -587, event: "Jeremiah"},
	{yearStart: -612, yearEnd: -612, event: "Assyrian Empire Destroyed and overthrown by the Babylonian Empire."},
	{ yearStart: -600, yearEnd: -500, event: "Ezekiel"},
	{ yearStart: -586, yearEnd: -586, event: "First Temple Destroyed. Babylon concurred Judah. Solomons Temple destroyed. Jewish Exile to Babylon. King Nebuchadnezzar began his rule."},
	{ yearStart: -538, yearEnd: -538, event: "Babylonian Empire fell to Persia. Achemenid Empire began. Cyrus allows Jewish Return to Zion. Temple Rebuilt. Oral Torah Written."},
	{ yearStart: -515, yearEnd: -515, event: "Second Temple Completed"},
	{ yearStart: -537, yearEnd: -530, event: "Ezra"},
	{ yearStart: -520, yearEnd: -520, event: "Haggai"},
	{ yearStart: -520, yearEnd: -520, event: "Zechariah"},
	{yearStart: -475, yearEnd: -424, event: "Esther"},
	{ yearStart: -427, yearEnd: -347, event: "Plato"},
	{ yearStart: -336, yearEnd: -323, event: "Alexander the Great (Babylonian - Mesopotamia)"},
	{yearStart: -334, yearEnd: -334, event: "Alexander the great conquests The Achemenid Empire which was devided amoung generals. Beginning of the Hellenistic Period."},  
	{ yearStart: -167, yearEnd: -140, event: "Maccabean Revolt"},
	{ yearStart: -198, yearEnd: -198, event: "The Seleucid Empire took control of Judea. Hellenized & religious Jews began to split. KIng Antiochus IV Epiphanes banned Jewish practice and desecrated the Temple via a pagan alter to Zeus. The Maccabees revolted and won."},
	{yearStart: -165, yearEnd: -165, event: "The Maccabees cleansed the Temple and rededicated it. The miracle of the oil occurred. Channukah was established. A new Jewish Dynasty was born:  the Hasmonean Dynasty."},
	{yearStart: -150, yearEnd: -100, event: `The Tenach "Cannonized". The Septuagint was written.`},
	{ yearStart: -72, yearEnd: -4, event: "Herod the Great"},
	{ yearStart: -63, yearEnd: -63, event: "Roman Empire conquered Judea"},
	{yearStart: -63, yearEnd: 73, event: "Roman Empire conquered Judea"},
	{ yearStart: 0, yearEnd: 33, event: "Life of Jesus"},
	{yearStart: 48, yearEnd: 48, event: "Burning of the Library of Alexandria."},
	{yearStart: 48, yearEnd: 51, event: "Pauls Early Letters (Galatians, 1 Thessalonians, 2 Thessalonians)"},
	{ yearStart: 50, yearEnd: 50, event: "Rabbi Akiva born."},
	{yearStart: 54, yearEnd: 56, event: "Pauls Major Letters (1 Corinthians, 2 Corinthians, Romans)"},
	{ yearStart: 60, yearEnd: 60, event: "Rabbi Yochanan ben Zakkai born."},
	{yearStart: 61, yearEnd: 62, event: "Pauls Prison Letters (Ephesians, Philippians, Colossians, Philemon)"},
	{yearStart: 62, yearEnd: 64, event: "Pauls Pastoral Letters (1 Timothy, 2 Timothy, Titus)"},
	{ yearStart: 63, yearEnd: 63, event: "Rabbi Shimon bar Yochai born."},
	{ yearStart: 66, yearEnd: 73, event: "Jewish Revolt. Jewish-Roman Revolt. Jewish Exile to Europe."},
	{yearStart: 66, yearEnd: 70, event: "Gospel of Mark"},
	{yearStart: 70, yearEnd: 640, event: "Talmudic Period."},
	{ yearStart: 70, yearEnd: 70, event: "Second Temple and Jeruselem's walls were Destroyed. Jewish Exile from Judea. Jewish Diaspora. Roman Empire destroyed Jerusalem. Masada fell to Rome. Jewish Revolt failed. Jewish Exile to Europe."},
	{ yearStart: 85, yearEnd: 90, event: "Gospel of Matthew and Luke"},
	{ yearStart: 90, yearEnd: 100, event: "Gospel of John"},
	{yearStart: 96, yearEnd: 96, event: "Book of Revelation"},
	{ yearStart: 100, yearEnd: 100, event: "Rabbi Yehuda HaNasi (Judah the Prince) compiled the Mishnah."},
	{ yearStart: 132, yearEnd: 135, event: "Bar Kokhba Revolt. Massive Jewish  depopulation. (580,000+)"},
	{ yearStart: 136, yearEnd: 136, event: "Rabbi Akiva is Martyred. Bar Kokhba Revolt. Jewish Exile to Europe. Rome renamed Judea to Syria Palaestina. (Palestine)"},
	{ yearStart: 200, yearEnd: 200, event: "(est) - Hebrew (as an informal language ceased being spoken) Hebrew was still consitantly studied from, and written through the Byzantine period until today. Torah has always been studied in Hebrew, without interruption, translation, or interpretation."},
	{ yearStart: 200, yearEnd: 300, event: "Talmud"},
	{ yearStart: 300, yearEnd: 400, event: "Jerome"},
	{yearStart: 301, yearEnd: 301, event: "Armenia becomes the first country to adopt Christianity as a state religion."},
	{yearStart: 300, yearEnd: 600, event: "Persecution and forced conversion to Christianity. Jewish Exile to Europe."},
	{yearStart: 325, yearEnd: 325, event: "Council of Nicaea. Trinity Doctrine established. Christianity becomes the official religion of the Roman Empire. Christianity adopted many pagan traditions (Winter Solstace, Ash Wednesday (mourning of Tammuz), Easter.)."},
	{yearStart: 350, yearEnd: 363, event: "The Christian Bible cannonized."},
	{yearStart: 400, yearEnd: 400, event: "The Babylonian Talmud was completed."},
	{yearStart: 500, yearEnd: 500, event: "The Jerusalem Talmud was completed."},
	{yearStart: 610, yearEnd: 632, event: "Muhammad. Islam was created."},
	{yearStart: 700, yearEnd: 700, event: "Arab Conquest, partially supported by Jews for hope of better treatment. (Forced conversions were only required of polytheists). Dome of the Rock was built on the Temple Mount."},
	{yearStart: 760, yearEnd: 760, event: "The Karaites reject the authority of the oral law and split from Rabbinic Judaism."},
	{yearStart: 800, yearEnd: 800, event: "Charlemagne (Christian Conquest)"},
	{yearStart: 846, yearEnd: 846, event: "Rav Amram Gaon compiles the first Siddur (Jewish Prayer Book)."},
	{yearStart: 940, yearEnd: 940, event: "Saadia Gaon complete's his Siddur (Jewish Prayer Book)."},
	{yearStart: 1040, yearEnd: 1105, event: "Rabbi Shlomo Yitzhaki (Rashi) writes his commentary on the Torah."},
	{yearStart: 1066, yearEnd: 1066, event: "Granada massacre. 4000+ Jews killed."},
	{yearStart: 1095, yearEnd: 1291, event: "Crusades occur. Grand massacre of Jews."},
	{yearStart: 1100, yearEnd: 1275, event: "The Tosafot were written."},
	{yearStart: 1135, yearEnd: 1204, event: "Rabbi Moses ben Maimon ( Rambam / Maimonides) - leader of Sephardic Jewry writes the Mishneh Torah."},
	{yearStart: 1200, yearEnd: 1200, event: "Ramban (Nachmanides)"},
	{yearStart: 1250, yearEnd: 1550, event: "Moses de Leon pubishes the Zohar (Kabbalah)."},
	{yearStart: 1346, yearEnd: 1353, event: "Jews blamed for the Black Death. Jews were Expelled from England"},
	{yearStart: 1478, yearEnd: 1834, event: "Tomas de Torquemada (Spanish Inquisition)"},
	{yearStart: 1483, yearEnd: 1546, event: "Martin Luther"},
	{yearStart: 1492, yearEnd: 1492, event: "Jews settle in he Ottoman Empire."},
	{yearStart: 1520, yearEnd: 1520, event: "Jerusalem's Old City Walls were built by Suleiman the Magnificent."},
	{yearStart: 1520, yearEnd: 1600, event: "Favorable migration policies in Eastern Europe. From Latvia, to Ukraine to Poland, incentivized many Jews to migrate."},
	{yearStart: 1648, yearEnd: 1654, event: "Khmelnytshy uprising in Ukraine. Ukrainians kill 100,000 - 300,000 Jews."},
	{yearStart: 1700, yearEnd: 1700, event: "Hasidic Judaism. The Baal Shem Tov. Russia aquires Poland, which now were unwelcoming of Jews living there."},
	{yearStart: 1703, yearEnd: 1758, event: "Jonathan Edwards. 1731 - Great Awakening. 1740 - First Great Awakening. 1741 - Sinners in the Hands of an Angry God."},
	{yearStart: 1800, yearEnd: 1850, event: "Jews killed in pogroms (Russian-anti-semetic waves of massacres) in Russia. Lots of Jews migrated to the United States."},
	{yearStart: 1858, yearEnd: 1922, event: "Eliezer Yitzhak Perelman Revived the Hebrew Language."},
	{yearStart: 1897, yearEnd: 1897, event: "Zionism. Great Britain's Basil Program attempted making Israel the Jewish homeland. Many Jews who didn't travel to the US, travelled to Europe (Germany, France, England)."},
	{yearStart: 1914, yearEnd: 1918, event: "WW1. Ottomans side with Germans"},
	{yearStart: 1918, yearEnd: 1939, event: "More Jews move to Israel a tensions escalate both between Germany and It's large Jewish population, as well as with the Arab Nations."},
	{yearStart: 1939, yearEnd: 1945, event: "WW2. 6 Million Jews killed in the Hollocaust."},
	{yearStart: 1948, yearEnd: 1948, event: "May 14, 1948 - Israel is re-established as the Jewish nation. David Ben Gurion as it's first prime minsiter."},
	{yearStart: 1948, yearEnd: 1952, event: "The Arab-Israeli War"},
	{yearStart: 1956, yearEnd: 1956, event: "The Suez Crisis (Second Arab-Israeli War)"},
	{yearStart: 1967, yearEnd: 1967, event: "The Six-Day War (Third Arab-Israeli War)"},
	{yearStart: 1973, yearEnd: 1973, event: "The Yom Kippur War (Fourth Arab-Israeli War)"},
	{yearStart: 1983, yearEnd: 1985, event: "War with Lebanon." },
	{yearStart: 2006, yearEnd: 2006, event: "War with Lebanon (Israel-Hezbollah War)." }
]

export default jewishHistory
