const mishnahRef = [
	{
		name: "zeraim",
		subject: "agriculture",
		sections: [
			{ section: "Berakhot", chapters: 9 },
			{ section: "Peah", chapters: 8 },
			{ section: "Demai", chapters: 7 },
			{ section: "Kilayim", chapters: 9 },
			{ section: "Sheviit", chapters: 10 },
			{ section: "Terumot", chapters: 11 },
			{ section: "Maasrot", chapters: 5 },
			{ section: "Maaser Sheni", chapters: 5 },
			{ section: "Hallah", chapters: 4 },
			{ section: "Orlah", chapters: 3 },
			{ section: "Bikkurim", chapters: 4 },
		],
	},
	{
		name: "moed",
		subject: "holidays",
		sections: [
			{ section: "Shabbat", chapters: 24 },
			{ section: "Eruvin", chapters: 10 },
			{ section: "Pesachim", chapters: 10 },
			{ section: "Shekalim", chapters: 8 },
			{ section: "Yoma", chapters: 8 },
			{ section: "Sukkah", chapters: 5 },
			{ section: "Beitzah", chapters: 5 },
			{ section: "Rosh Hashanah", chapters: 4 },
			{ section: "Taanit", chapters: 4 },
			{ name: "Megillah", chapters: 4 },
			{ section: "Moed Katan", chapters: 3 },
			{ section: "Chagigah", chapters: 3 },
		],
	},
	{
		name: "nashim",
		subject: "family law",
		sections: [
			{ section: "Yevamot", chapters: 16 },
			{ section: "Ketubot", chapters: 13 },
			{ section: "Nedarim", chapters: 11 },
			{ section: "Nazir", chapters: 9 },
			{ section: "Sotah", chapters: 9 },
			{ section: "Gittin", chapters: 9 },
			{ section: "Kiddushin", chapters: 4 },
		],
	},
	{
		name: "nezikin",
		subject: "damages",
		sections: [
			{ section: "Bava Kamma", chapters: 10 },
			{ section: "Bava Metzia", chapters: 10 },
			{ section: "Bava Batra", chapters: 10 },
			{ section: "Sanhedrin", chapters: 11 },
			{ section: "Makkot", chapters: 3 },
			{ section: "Shevuot", chapters: 8 },
			{ section: "Eduyot", chapters: 8 },
			{ section: "Avodah Zarah", chapters: 5 },
			{ section: "Avot", chapters: 5 },
			{ section: "Horayot", chapters: 3 },
		],
	},
	{
		name: "kodshim",
		subject: "sacrifices",
		sections: [
			{ section: "Zevachim", chapters: 14 },
			{ section: "Menachot", chapters: 13 },
			{ section: "Chullin", chapters: 12 },
			{ section: "Bechorot", chapters: 9 },
			{ section: "Arachin", chapters: 9 },
			{ section: "Temurah", chapters: 7 },
			{ section: "Keritot", chapters: 6 },
			{ section: "Meilah", chapters: 6 },
			{ section: "Tamid", chapters: 7 },
			{ section: "Middot", chapters: 5 },
			{ section: "Kinnim", chapters: 3 },
		],
	},
	{
		name: "Tahorot",
		subject: "purity",
		sections: [
			{ section: "Keilim", chapters: 30 },
			{ section: "Oholot", chapters: 18 },
			{ section: "Negaim", chapters: 14 },
			{ section: "Parah", chapters: 12 },
			{ section: "Tohorot", chapters: 12 },
			{ section: "Mikvaot", chapters: 10 },
			{ section: "Niddah", chapters: 10 },
			{ section: "Machshirin", chapters: 6 },
			{ section: "Zavim", chapters: 5 },
			{ section: "Tevul Yom", chapters: 4 },
			{ section: "Yadayim", chapters: 4 },
			{ section: "Uktzin", chapters: 3 },
		],
	},
]

export default mishnahRef
